name: CI demo

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ vars.BASE_URL }}
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Playwright browser
        uses: python -m playwright install chromium

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest -v
